"""Validate placeholder coverage and emit the offline JVM/Android resource catalogs."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
CAT = ROOT / 'localization/catalog'
OUT = ROOT / 'localization/src/main/resources/openavm-i18n'
LOCALES = ('zh-TW', 'th', 'vi', 'ar')

def escape(value):
    return value.replace('\\', '\\\\').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t').replace(' ', '\\ ')

def main():
    source = json.loads((CAT / 'source.json').read_text(encoding='utf-8'))
    terminology = json.loads((CAT / 'terminology.json').read_text(encoding='utf-8'))
    OUT.mkdir(parents=True, exist_ok=True)
    summary = {}
    for locale in ('en', 'zh-CN', *LOCALES):
        values = {key: item[locale] for key, item in source.items()} if locale in ('en','zh-CN') else json.loads((CAT / (locale+'.json')).read_text(encoding='utf-8'))
        lines = ['# Generated by localization/generate.py; UTF-8. Edit catalog JSON, then regenerate.']
        for key, item in sorted(source.items()):
            if locale in LOCALES and item['en'] in terminology:
                values[key] = terminology[item['en']][LOCALES.index(locale)]
            assert key in values and values[key], (locale, key, item['en'])
            expected = set(re.findall(r'\{\d+\}', item['zh-CN'] if locale in ('zh-CN','zh-TW') else item['en']))
            assert set(re.findall(r'\{\d+\}', values[key])) == expected, (locale, key, 'placeholder mismatch')
            assert not re.search(r'QXQ\d{4}QXQ', values[key]), (locale, key, 'translation delimiter leaked')
            lines.append(key + '=' + escape(values[key]))
        (OUT / (locale+'.properties')).write_text('\n'.join(lines)+'\n', encoding='utf-8')
        summary[locale] = len(source)
    report = ROOT / 'build/localization-coverage.json'
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps(summary, indent=2), encoding='utf-8')
    print(json.dumps(summary))

if __name__ == '__main__': main()
